export const types = {
  
  VIEW_POST_REQUESTED: "VIEW_POST_REQUESTED",
  VIEW_POST_SUCCESS: "VIEW_POST_SUCCESS",
  VIEW_POST_FAILURE: "VIEW_POST_FAILURE",

  CREATE_POST_REQUESTED: "CREATE_POST_REQUESTED",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

  UPDATE_POST_REQUESTED: "UPDATE_POST_REQUESTED",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",

  DELETE_POST_REQUESTED: "DELETE_POST_REQUESTED",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
};
